services:
  # ----------------------------------------
  # 1. SERVICIO DE BASE DE DATOS (POSTGRES)
  # ----------------------------------------
  db:
    image: postgres:16-alpine
    container_name: postgres_cartones_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ----------------------------------------
  # 2. SERVICIO DEL BACKEND (SPRING BOOT)
  # ----------------------------------------
  backend:
    build: .
    container_name: cartones_backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: