services:
  # ==========================================
  # 1. BASE DE DATOS
  # ==========================================
  db:
    image: postgres:16-alpine
    container_name: postgres_cartones_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "127.0.0.1:${PORT_DB}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user)"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # 2. BACKEND APP
  # ==========================================
  backend:
    build:
      context: .
    container_name: cartones_backend
    restart: always
    environment:
      SERVER_PORT: 9001

      # --- PERFIL ACTIVO (DEV/PROD) ---
      SPRING_PROFILES_ACTIVE: ${APP_PROFILE}

      # --- INYECCIÓN DE VARIABLES DEL .ENV ---
      APP_DDL_AUTO: ${DB_DDL_AUTO}
      APP_SHOW_SQL: ${DB_SHOW_SQL}
      APP_LOG_LEVEL: ${LOG_LEVEL}
      APP_OPEN_IN_VIEW: ${OPEN_IN_VIEW}
      APP_CORS_ORIGINS: ${FRONTEND_URL}

      # --- CONEXIÓN DB ---
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      # Importar secretos automáticamente como propiedades
      SPRING_CONFIG_IMPORT: "configtree:/run/secrets/"

    ports:
      - "${PORT_BACKEND}:9001"
    depends_on:
      db:
        condition: service_healthy
    secrets:
      # TRUCO: Montamos el archivo con el nombre de la propiedad de Spring
      - source: db_user
        target: spring.datasource.username
      - source: db_password
        target: spring.datasource.password

volumes:
  postgres_data:

secrets:
  db_user:
    file: ./secrets_store/db_user.txt
  db_password:
    file: ./secrets_store/db_password.txt