services:
  db:
    image: postgres:16-alpine
    container_name: postgres_cartones_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "127.0.0.1:${PORT_DB}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - source: db_user
        target: db_user
        mode: 0444
      - source: db_password
        target: db_password
        mode: 0444
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: cartones_backend
    restart: always
    environment:
      SERVER_PORT: 9001
      SPRING_PROFILES_ACTIVE: ${APP_PROFILE}

      # Variables inyectadas
      APP_DDL_AUTO: ${DB_DDL_AUTO}
      APP_SHOW_SQL: ${DB_SHOW_SQL}
      APP_LOG_LEVEL: ${LOG_LEVEL}
      APP_OPEN_IN_VIEW: ${OPEN_IN_VIEW}
      APP_CORS_ORIGINS: ${FRONTEND_URL}

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_CONFIG_IMPORT: "configtree:/run/secrets/"

    ports:
      - "${PORT_BACKEND}:9001"
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - source: db_user
        target: spring.datasource.username
        mode: 0444
      - source: db_password
        target: spring.datasource.password
        mode: 0444

volumes:
  postgres_data:

secrets:
  db_user:
    file: ./secrets_store/db_user.txt
  db_password:
    file: ./secrets_store/db_password.txt